version: '3.8'

services:
  image-upload-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elders-guild-image-upload-manager
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app/app.py
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - elders-guild-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  elders-guild-network:
    driver: bridge

volumes:
  upload_data:
    driver: local
