# Elders Guild - Development Override
# 開発時の追加設定・デバッグ用

version: '3.8'

services:
  # 開発時の追加設定
  postgres:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./dev-data:/tmp/dev-data
    ports:
      - "5432:5432"  # 開発時は標準ポートも公開

  redis:
    ports:
      - "6379:6379"  # 開発時は標準ポートも公開

  # 開発時のデバッグサービス
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: elders-guild-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eldersguild.ai
      - PGADMIN_DEFAULT_PASSWORD=sage_wisdom_2025
    ports:
      - "8888:80"
    depends_on:
      - postgres
    networks:
      - elders-network
    profiles:
      - debug

  # Redis Commander（デバッグ用）
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: elders-guild-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8889:8081"
    depends_on:
      - redis
    networks:
      - elders-network
    profiles:
      - debug

  # ログ集約（開発用）
  log-aggregator:
    image: grafana/loki:2.9.0
    container_name: elders-guild-logs
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki.yml:/etc/loki/local-config.yaml
    networks:
      - elders-network
    profiles:
      - debug

networks:
  elders-network:
    external: true
