---
# Elder Sage報告機能設定
# Four Sagesからの統合レポート生成

sage_reports:
  enabled: true
  report_interval: 3600  # 1時間ごと
  
# Incident Sage レポート設定
incident_sage_reports:
  name: "Incident Sage Activity Report"
  enabled: true
  
  metrics:
    - total_incidents:
        description: "検知したインシデント総数"
        aggregation: count
        
    - resolved_incidents:
        description: "解決済みインシデント数"
        aggregation: count
        filter: "status == 'resolved'"
        
    - avg_resolution_time:
        description: "平均解決時間"
        aggregation: average
        unit: seconds
        
    - auto_recovery_rate:
        description: "自動回復成功率"
        aggregation: percentage
        
    - incident_by_severity:
        description: "重要度別インシデント数"
        aggregation: group_by
        field: severity
        
    - top_error_patterns:
        description: "頻出エラーパターンTOP10"
        aggregation: top_n
        n: 10
        
  sections:
    - summary:
        title: "インシデント概要"
        include:
          - total_incidents
          - resolved_incidents
          - avg_resolution_time
          - auto_recovery_rate
          
    - details:
        title: "詳細分析"
        include:
          - incident_by_severity
          - top_error_patterns
          - timeline_chart
          
    - recommendations:
        title: "改善提案"
        auto_generate: true
        based_on:
          - recurring_incidents
          - slow_resolution_patterns

# Knowledge Sage レポート設定
knowledge_sage_reports:
  name: "Knowledge Sage Learning Report"
  enabled: true
  
  metrics:
    - knowledge_entries:
        description: "知識エントリー総数"
        aggregation: count
        
    - new_entries_added:
        description: "新規追加エントリー数"
        aggregation: count
        time_range: report_period
        
    - embeddings_generated:
        description: "生成された埋め込みベクトル数"
        aggregation: count
        
    - storage_usage:
        description: "ストレージ使用量"
        aggregation: current
        unit: GB
        
    - query_performance:
        description: "クエリ応答性能"
        aggregation: percentile
        percentiles: [50, 90, 99]
        unit: milliseconds
        
    - knowledge_categories:
        description: "カテゴリ別知識分布"
        aggregation: distribution
        
  sections:
    - growth:
        title: "知識ベース成長"
        include:
          - knowledge_entries
          - new_entries_added
          - growth_trend_chart
          
    - performance:
        title: "パフォーマンス"
        include:
          - query_performance
          - embeddings_generated
          - storage_usage
          
    - insights:
        title: "学習インサイト"
        include:
          - knowledge_categories
          - popular_topics
          - knowledge_gaps

# Task Sage レポート設定
task_sage_reports:
  name: "Task Sage Management Report"
  enabled: true
  
  metrics:
    - total_tasks:
        description: "処理タスク総数"
        aggregation: count
        
    - completed_tasks:
        description: "完了タスク数"
        aggregation: count
        filter: "status == 'completed'"
        
    - completion_rate:
        description: "タスク完了率"
        aggregation: percentage
        
    - avg_task_duration:
        description: "平均タスク処理時間"
        aggregation: average
        unit: seconds
        
    - queue_length:
        description: "現在のキュー長"
        aggregation: current
        
    - worker_utilization:
        description: "ワーカー使用率"
        aggregation: average
        unit: percentage
        
    - task_distribution:
        description: "タスクタイプ別分布"
        aggregation: distribution
        
  sections:
    - efficiency:
        title: "処理効率"
        include:
          - total_tasks
          - completed_tasks
          - completion_rate
          - avg_task_duration
          
    - workload:
        title: "ワークロード分析"
        include:
          - queue_length
          - worker_utilization
          - task_distribution
          - peak_hours_analysis
          
    - optimization:
        title: "最適化提案"
        include:
          - bottleneck_analysis
          - resource_recommendations

# RAG Sage レポート設定
rag_sage_reports:
  name: "RAG Sage Retrieval Report"
  enabled: true
  
  metrics:
    - total_queries:
        description: "検索クエリ総数"
        aggregation: count
        
    - avg_response_time:
        description: "平均応答時間"
        aggregation: average
        unit: milliseconds
        
    - retrieval_accuracy:
        description: "検索精度"
        aggregation: percentage
        
    - cache_hit_rate:
        description: "キャッシュヒット率"
        aggregation: percentage
        
    - index_size:
        description: "インデックスサイズ"
        aggregation: current
        unit: documents
        
    - popular_queries:
        description: "人気検索クエリTOP20"
        aggregation: top_n
        n: 20
        
  sections:
    - performance:
        title: "検索パフォーマンス"
        include:
          - total_queries
          - avg_response_time
          - cache_hit_rate
          
    - quality:
        title: "検索品質"
        include:
          - retrieval_accuracy
          - relevance_scores
          - user_satisfaction
          
    - trends:
        title: "検索トレンド"
        include:
          - popular_queries
          - query_patterns
          - seasonal_variations

# 統合レポート設定
integrated_report:
  name: "Elder Tree System Integrated Report"
  enabled: true
  frequency: "daily"  # daily, weekly, monthly
  
  sections:
    - executive_summary:
        title: "エグゼクティブサマリー"
        content:
          - system_health_score
          - key_metrics_dashboard
          - critical_alerts_summary
          - action_items
          
    - sage_performance:
        title: "Four Sages パフォーマンス"
        subsections:
          - incident_sage_summary
          - knowledge_sage_summary
          - task_sage_summary
          - rag_sage_summary
          
    - system_health:
        title: "システム健全性"
        content:
          - elder_tree_connectivity
          - worker_pool_status
          - resource_utilization
          - error_rates
          
    - trends_analysis:
        title: "トレンド分析"
        content:
          - performance_trends
          - capacity_planning
          - predictive_insights
          
    - recommendations:
        title: "改善提案"
        content:
          - immediate_actions
          - short_term_improvements
          - long_term_strategy

# レポート配信設定
report_delivery:
  formats:
    - html:
        enabled: true
        template: "elder_tree_report_template.html"
        
    - pdf:
        enabled: true
        include_charts: true
        
    - json:
        enabled: true
        raw_data: false
        
  destinations:
    - email:
        enabled: true
        recipients:
          - "admin@aicompany.com"
          - "elder-council@aicompany.com"
        schedule:
          daily: "09:00"
          weekly: "monday 09:00"
          monthly: "1st 09:00"
          
    - slack:
        enabled: true
        channels:
          - "#elder-reports"
          - "#system-health"
        summary_only: true
        
    - dashboard:
        enabled: true
        url: "/monitoring/reports/latest"
        auto_refresh: true
        
    - s3:
        enabled: false
        bucket: "elder-tree-reports"
        prefix: "reports/"
        retention_days: 90

# レポート生成オプション
generation_options:
  parallel_processing: true
  cache_intermediate_results: true
  include_raw_data: false
  compress_large_reports: true
  
  visualization:
    chart_library: "plotly"
    color_scheme: "elder_tree"
    interactive_charts: true
    
  quality_checks:
    validate_data_completeness: true
    check_anomalies: true
    flag_missing_metrics: true