services:
  # 既存のエルダーズギルドPostgreSQLを使用
  # ポート8003で起動済み
  
  # 既存のエルダーズギルドRedisを使用  
  # ポート8004で起動済み
  
  backend:
    image: python:3.11-slim
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://elders:elders@host.docker.internal:8003/elders_guild
      - REDIS_URL=redis://host.docker.internal:8004
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - upload_data:/app/uploads
    working_dir: /app
    command: >
      bash -c "
        pip install -r requirements.txt &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: node:18-alpine
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npm start
      "
    depends_on:
      - backend

volumes:
  upload_data: