# -*- coding: utf-8 -*-

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/error_details.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(

)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "google.rpc.error_details_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\016com.google.rpcB\021ErrorDetailsProtoP\001Z?google.golang.org/genproto/googleapis/rpc/errdetails;errdetails\242\002\003RPC"
    _globals["_ERRORINFO_METADATAENTRY"]._options = None
    _globals["_ERRORINFO_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_QUOTAFAILURE_VIOLATION_QUOTADIMENSIONSENTRY"]._options = None
    _globals[
        "_QUOTAFAILURE_VIOLATION_QUOTADIMENSIONSENTRY"
    ]._serialized_options = b"8\001"
    _globals["_ERRORINFO"]._serialized_start = 79
    _globals["_ERRORINFO"]._serialized_end = 226
    _globals["_ERRORINFO_METADATAENTRY"]._serialized_start = 179
    _globals["_ERRORINFO_METADATAENTRY"]._serialized_end = 226
    _globals["_RETRYINFO"]._serialized_start = 228
    _globals["_RETRYINFO"]._serialized_end = 287

    _globals["_QUOTAFAILURE"]._serialized_start = 342
    _globals["_QUOTAFAILURE"]._serialized_end = 741
    _globals["_QUOTAFAILURE_VIOLATION"]._serialized_start = 415
    _globals["_QUOTAFAILURE_VIOLATION"]._serialized_end = 741
    _globals["_QUOTAFAILURE_VIOLATION_QUOTADIMENSIONSENTRY"]._serialized_start = 664
    _globals["_QUOTAFAILURE_VIOLATION_QUOTADIMENSIONSENTRY"]._serialized_end = 718
    _globals["_PRECONDITIONFAILURE"]._serialized_start = 744
    _globals["_PRECONDITIONFAILURE"]._serialized_end = 893
    _globals["_PRECONDITIONFAILURE_VIOLATION"]._serialized_start = 830
    _globals["_PRECONDITIONFAILURE_VIOLATION"]._serialized_end = 893
    _globals["_BADREQUEST"]._serialized_start = 896
    _globals["_BADREQUEST"]._serialized_end = 1100
    _globals["_BADREQUEST_FIELDVIOLATION"]._serialized_start = 975
    _globals["_BADREQUEST_FIELDVIOLATION"]._serialized_end = 1100
    _globals["_REQUESTINFO"]._serialized_start = 1102
    _globals["_REQUESTINFO"]._serialized_end = 1157
    _globals["_RESOURCEINFO"]._serialized_start = 1159
    _globals["_RESOURCEINFO"]._serialized_end = 1255
    _globals["_HELP"]._serialized_start = 1257
    _globals["_HELP"]._serialized_end = 1343
    _globals["_HELP_LINK"]._serialized_start = 1303
    _globals["_HELP_LINK"]._serialized_end = 1343
    _globals["_LOCALIZEDMESSAGE"]._serialized_start = 1345
    _globals["_LOCALIZEDMESSAGE"]._serialized_end = 1396
# @@protoc_insertion_point(module_scope)
