global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Elders Guild API Server
  - job_name: 'elders-guild-api'
    static_configs:
      - targets: ['api-server:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s

  # Event Bus Worker
  - job_name: 'event-worker'
    static_configs:
      - targets: ['event-worker:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Custom Application Metrics
  - job_name: 'elders-guild-custom'
    static_configs:
      - targets: ['api-server:8000']
    metrics_path: '/api/v2/system/metrics'
    scrape_interval: 30s
