#!/bin/bash
# AI Company 新コマンド使用例

echo "🎯 AI Company 新コマンド使用例"
echo "=============================="

echo -e "\n[1] ログ確認コマンド (ai-logs)"
echo "------------------------------"
echo "# 全ログの最新20行を表示"
echo "ai-logs"
echo ""
echo "# タスクワーカーのログをリアルタイム追跡"
echo "ai-logs task -f"
echo ""
echo "# エラーログのみ表示"
echo "ai-logs --error"
echo ""
echo "# 特定のタスクIDのログを検索"
echo "ai-logs --task-id code_20250701_123456"
echo ""
echo "# 過去1時間のログを表示"
echo "ai-logs --since 1h --lines 50"

echo -e "\n[2] タスク管理コマンド (ai-tasks)"
echo "---------------------------------"
echo "# 最新10件のタスク一覧"
echo "ai-tasks"
echo ""
echo "# コードタスクのみ表示"
echo "ai-tasks --type code --limit 20"
echo ""
echo "# 特定タスクの詳細表示"
echo "ai-tasks --task-id code_20250701_123456"
echo ""
echo "# 会話タスクの詳細"
echo "ai-tasks --conversation conv_dialog_20250701_123456"
echo ""
echo "# JSON形式で出力（プログラム連携用）"
echo "ai-tasks --json --limit 5"

echo -e "\n[3] 対話型タスクコマンド (ai-dialog & ai-reply)"
echo "-----------------------------------------------"
echo "# 対話型タスクの開始"
echo "ai-dialog \"複雑なECサイトを作成したい。要件を相談しながら進めたい\""
echo ""
echo "# 応答の送信（会話IDを使用）"
echo "ai-reply conv_dialog_20250701_123456 \"商品管理、ユーザー認証、決済機能が必要です\""
echo ""
echo "# ファイルから応答を読み込み"
echo "ai-reply conv_dialog_20250701_123456 --file requirements.txt"

echo -e "\n[4] 組み合わせ使用例"
echo "-------------------"
echo "# タスクを送信して、ログで進捗確認"
echo "ai-send \"データベース設計書を作成\" report && ai-logs task -f"
echo ""
echo "# 最近のエラーを確認してからシステム再起動"
echo "ai-logs --error --since 30m && ai-stop && ai-start"
echo ""
echo "# 対話開始後、タスク状態を確認"
echo "ai-dialog \"APIサーバーを構築したい\" && sleep 5 && ai-tasks --limit 1"

echo -e "\n💡 ヒント:"
echo "- 各コマンドの詳細は --help オプションで確認できます"
echo "- ai-logs の -f オプションは Ctrl+C で停止します"
echo "- ai-tasks の結果はパイプで他のコマンドに渡せます"
echo ""
