global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'elder-flow-api'
    static_configs:
      - targets: ['elder-flow:9090']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'elder-flow-workers'
    static_configs:
      - targets:
        - 'elder-servant:9091'
        - 'knowledge-sage:9092'
        - 'task-sage:9093'
        - 'incident-sage:9094'
        - 'rag-sage:9095'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alerts.yml"
