# 99.999% Uptime - Critical Workers Redundancy Configuration
# 重要ワーカーの冗長化設定

critical_workers:
  # Core system workers requiring high availability
  worker_health_monitor:
    instances: 2
    priority: 1
    auto_failover: true
    health_check_interval: 5

  task_dispatcher:
    instances: 3
    priority: 1
    auto_failover: true
    health_check_interval: 5

  queue_processor:
    instances: 2
    priority: 2
    auto_failover: true
    health_check_interval: 10

  elder_council_manager:
    instances: 2
    priority: 1
    auto_failover: true
    health_check_interval: 15

redundancy_settings:
  # Load balancing strategy
  load_balancing: "round_robin"

  # Failover settings
  failover_timeout: 10  # seconds
  health_check_failures_threshold: 2

  # Instance management
  restart_failed_instances: true
  max_restart_attempts: 3
  restart_delay: 30  # seconds

  # Monitoring
  monitor_instance_performance: true
  performance_threshold:
    cpu_usage: 80.0
    memory_usage: 85.0
    response_time: 5.0  # seconds

# High availability features for 99.999% uptime
high_availability:
  enable_circuit_breaker: true
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60

  enable_graceful_shutdown: true
  shutdown_timeout: 30

  enable_rolling_updates: true
  update_strategy: "blue_green"

  # Zero-downtime deployment
  enable_zero_downtime_deployment: true
  deployment_strategy: "canary"
  canary_percentage: 10

# Notification settings for high availability events
notifications:
  instance_failure:
    enabled: true
    severity: "high"
    channels: ["slack", "email"]

  failover_event:
    enabled: true
    severity: "medium"
    channels: ["slack"]

  performance_degradation:
    enabled: true
    severity: "medium"
    channels: ["slack"]

# Emergency procedures
emergency_procedures:
  auto_scale_on_failure: true
  emergency_instance_spawn: true
  emergency_contact_elder_council: true
  emergency_notification_threshold: 2  # failed instances
