global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'elder-tree'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Elder Tree Services (discovered via Consul)
  - job_name: 'elder-tree-services'
    consul_sd_configs:
      - server: 'consul:8500'
        services:
          - 'knowledge-sage'
          - 'task-sage'
          - 'incident-sage'
          - 'rag-sage'
          - 'elder-flow'
          - 'code-crafter'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: service
      - source_labels: [__meta_consul_node]
        target_label: node
      - source_labels: [__meta_consul_tags]
        target_label: tags

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel_collector:8888']

  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Redis exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - '/etc/prometheus/rules/*.yml'