# EITMS (Elders Guild Integrated Task Management System) Configuration
# エルダーズギルド統合タスク管理システム設定

system:
  name: "EITMS"
  version: "1.0.0"
  environment: "development"
  debug: true
  log_level: "INFO"

# データベース設定
database:
  # メインデータベース（統一データモデル）
  main:
    type: "sqlite"
    path: "/home/aicompany/ai_co/data/eitms.db"
    # PostgreSQL使用時
    # type: "postgresql"
    # host: "localhost"
    # port: 5432
    # database: "eitms"
    # user: "eitms_user"
    # password: "${EITMS_DB_PASSWORD}"
  
  # ベクトルデータベース（RAG賢者用）
  vector:
    type: "pgvector"
    host: "localhost"
    port: 5432
    database: "eitms_vector"
    user: "eitms_vector_user"
    password: "${EITMS_VECTOR_DB_PASSWORD}"

# API統合設定
integrations:
  # GitHub統合
  github:
    enabled: true
    api_url: "https://api.github.com"
    token: "${GITHUB_TOKEN}"
    webhook_secret: "${GITHUB_WEBHOOK_SECRET}"
    default_owner: "ext-maru"
    default_repo: "ai-co"
    
  # TaskTracker統合
  task_tracker:
    enabled: true
    api_url: "http://localhost:8080/api"
    api_key: "${TASK_TRACKER_API_KEY}"
    
  # Todo統合
  todo:
    enabled: true
    api_url: "http://localhost:8081/api"
    api_key: "${TODO_API_KEY}"

# AI最適化設定
ai_optimization:
  enabled: true
  learning_enabled: true
  auto_optimization: true
  
  # 複雑度分析
  complexity_analysis:
    keywords_weight_multiplier: 1.0
    max_complexity_score: 5.0
    
  # 工数見積もり
  effort_estimation:
    base_hours:
      todo: 0.5
      project_task: 4.0
      issue: 8.0
      planning: 2.0
    
  # 優先度最適化
  priority_optimization:
    urgency_boost_max: 3.0
    business_value_weight: 1.5

# 監視設定
monitoring:
  enabled: true
  health_check_interval: 300  # 5分
  consistency_check_interval: 600  # 10分
  
  # アラート設定
  alerts:
    enabled: true
    channels:
      - type: "log"
      - type: "slack"
        webhook_url: "${SLACK_WEBHOOK_URL}"
    
    thresholds:
      critical_incidents: 1
      high_incidents: 5
      inconsistencies: 10
      recovery_failures: 3

# 同期設定
synchronization:
  # イベントバス設定
  event_bus:
    type: "memory"  # memory, redis, rabbitmq
    redis_url: "redis://localhost:6379"
    
  # 自動同期ルール
  cascade_rules:
    - source: "issue"
      target: "project_task"
      enabled: true
      auto_create: true
      
    - source: "project_task"
      target: "todo"
      enabled: true
      auto_create: true
      
    - source: "planning"
      target: "issue"
      enabled: true
      auto_create: false

# サービス設定
services:
  # APIサーバー
  api:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    
  # 監視ダッシュボード
  dashboard:
    enabled: false  # グランドエルダーmaru様の指示によりGUI禁止
    
  # Webhookレシーバー
  webhook:
    host: "0.0.0.0"
    port: 8888
    path: "/webhooks"

# セキュリティ設定
security:
  # API認証
  api_auth:
    enabled: true
    type: "bearer"
    token_expiry: 3600
    
  # 暗号化
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key: "${EITMS_ENCRYPTION_KEY}"

# ログ設定
logging:
  # ログ出力先
  handlers:
    - type: "file"
      path: "/home/aicompany/ai_co/logs/eitms.log"
      level: "INFO"
      rotation: "daily"
      retention: 30
      
    - type: "console"
      level: "DEBUG"
      format: "colored"

# 4賢者設定
four_sages:
  # ナレッジ賢者
  knowledge:
    database: "/home/aicompany/ai_co/data/knowledge_sage.db"
    index_path: "/home/aicompany/ai_co/data/knowledge_index"
    
  # タスク賢者
  task:
    database: "/home/aicompany/ai_co/data/task_sage.db"
    optimization_interval: 3600
    
  # インシデント賢者
  incident:
    database: "/home/aicompany/ai_co/data/incident_sage.db"
    alert_threshold: "medium"
    
  # RAG賢者
  rag:
    database: "/home/aicompany/ai_co/data/rag_sage.db"
    vector_dimension: 1536
    similarity_threshold: 0.8

# パフォーマンス設定
performance:
  # 接続プール
  connection_pool:
    min_size: 10
    max_size: 100
    
  # キャッシュ
  cache:
    type: "redis"
    ttl: 3600
    
  # レート制限
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst: 10

# 開発設定（本番環境では無効化）
development:
  # モックモード
  mock_external_apis: false
  
  # テストデータ
  seed_test_data: false
  
  # デバッグツール
  enable_profiling: false
  enable_debug_endpoints: true