# Worker Auto-Recovery System Configuration

recovery:
  check_interval: 30           # Health check interval in seconds
  max_retries: 3              # Maximum recovery attempts
  retry_delay: 10             # Delay between retries in seconds
  cooldown_period: 300        # Cooldown period after recovery (5 minutes)

health_check:
  thresholds:
    cpu_percent: 90.0         # CPU usage threshold
    memory_mb: 1024           # Memory usage threshold in MB
    error_rate: 0.1           # Error rate threshold (10%)
    queue_size: 100           # Queue size threshold
    response_timeout: 30      # Response timeout in seconds
  
  check_interval: 30          # Individual check interval
  history_size: 100           # Number of history entries to keep

notification:
  slack_enabled: true         # Enable Slack notifications
  log_enabled: true           # Enable log notifications
  elder_notification: true    # Notify Elder Council for critical issues
  
  severity_levels:
    info: '📘'
    warning: '⚠️'
    error: '🚨'
    critical: '🔴'

workers:
  task_worker:
    enabled: true
    critical: true
    script: '/home/aicompany/ai_co/workers/enhanced_task_worker.py'
    
  pm_worker:
    enabled: true
    critical: true
    script: '/home/aicompany/ai_co/workers/intelligent_pm_worker_simple.py'
    
  result_worker:
    enabled: true
    critical: true
    script: '/home/aicompany/ai_co/workers/async_result_worker_simple.py'
    
  error_intelligence_worker:
    enabled: true
    critical: false
    script: '/home/aicompany/ai_co/workers/error_intelligence_worker.py'
    
  slack_polling_worker:
    enabled: true
    critical: false
    script: '/home/aicompany/ai_co/workers/slack_polling_worker.py'

strategies:
  default: soft_restart       # Default recovery strategy
  emergency: hard_restart     # Emergency recovery strategy
  
  priority_map:
    process_not_found: cold_start
    high_resource_usage: resource_recovery
    queue_overflow: queue_recovery
    low_health_score: hard_restart