# Elder Scheduler設定ファイル
# APScheduler統合による定期実行タスクの設定

# スケジューラー基本設定
scheduler:
  type: asyncio  # asyncio, background, blocking
  timezone: Asia/Tokyo
  max_workers: 20
  
# ジョブストア設定
jobstores:
  default:
    type: memory
  redis:
    enabled: false
    host: localhost
    port: 6379
    db: 1
  postgres:
    enabled: false
    url: postgresql://postgres:password@localhost:5432/ai_company

# ジョブデフォルト設定
job_defaults:
  coalesce: true  # 同一ジョブの重複実行を防ぐ
  max_instances: 3  # 最大同時実行数
  misfire_grace_time: 30  # 実行遅延許容時間（秒）

# タスク設定
tasks:
  # システム保守タスク
  system_maintenance:
    cleanup:
      enabled: true
      schedule: "0 2 * * *"  # 毎日深夜2時
    backup:
      enabled: true
      schedule: "0 3 * * *"  # 毎日深夜3時
    security_scan:
      enabled: true
      schedule: "0 4 * * *"  # 毎日深夜4時
      
  # データベース管理タスク
  database:
    optimization:
      enabled: true
      schedule: "30 1 * * *"  # 毎日深夜1時30分
    statistics_update:
      enabled: true
      interval_hours: 6
      
  # 監視・ヘルスチェックタスク
  monitoring:
    health_check:
      enabled: true
      interval_minutes: 30
    performance:
      enabled: true
      interval_hours: 1
      
  # nWo関連タスク
  nwo:
    daily_council:
      enabled: true
      schedule: "0 9 * * *"  # 毎日9時
    weekly_strategy:
      enabled: true
      schedule: "0 10 * * 1"  # 月曜10時
      
  # 知識ベース管理タスク
  knowledge:
    sync:
      enabled: true
      schedule: "0 1 * * *"  # 毎日深夜1時
    learning:
      enabled: true
      interval_hours: 6
      
  # レポート生成タスク
  reporting:
    daily:
      enabled: true
      schedule: "30 8 * * *"  # 毎日8時30分
    weekly:
      enabled: true
      schedule: "0 9 * * 1"  # 月曜9時
      
  # GitHub自動処理タスク
  github:
    auto_issue_processor:
      enabled: false  # 現在無効化中（テスト完了後に有効化）
      interval_minutes: 10
      config:
        max_issues_per_run: 1
        dry_run: false
        features:
          pr_creation: true
          error_recovery: true
          parallel_processing: false  # スケジューラー実行時は無効推奨
          four_sages_integration: true
    health_check:
      enabled: true
      interval_hours: 1

# ログ設定
logging:
  level: INFO
  file: logs/elder_scheduler.log
  max_bytes: 10485760  # 10MB
  backup_count: 5