version: '3.8'

services:
  # Contract Upload Backend (FastAPI)
  contract-upload-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elders-guild-contract-upload-backend
    restart: always
    environment:
      - ENV=production
      - DATABASE_URL=sqlite:///app/data/contract_upload.db
      - UPLOAD_DIR=/app/uploads
      - SECRET_KEY_FILE=/app/config/secret_key.txt
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./config:/app/config
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.7'
        reservations:
          memory: 512M
          cpus: '0.3'
    networks:
      - contract-upload-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Contract Upload Frontend (React)
  contract-upload-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elders-guild-contract-upload-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://57.181.4.111:8000
    ports:
      - "3000:3000"
    depends_on:
      - contract-upload-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    networks:
      - contract-upload-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  contract-upload-network:
    driver: bridge

volumes:
  contract_data:
    driver: local
  contract_uploads:
    driver: local
