apiVersion: apps/v1
kind: Deployment
metadata:
  name: elder-flow-api
  namespace: elder-flow
  labels:
    app: elder-flow
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elder-flow
      component: api
  template:
    metadata:
      labels:
        app: elder-flow
        component: api
    spec:
      containers:
      - name: elder-flow-api
        image: elderflow/elder-flow:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: ELDER_FLOW_ENV
          valueFrom:
            configMapKeyRef:
              name: elder-flow-config
              key: ELDER_FLOW_ENV
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: elder-flow-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: elder-flow-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: elder-flow-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elder-flow-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: elder-flow-config
              key: REDIS_HOST
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: elder-flow-secrets
              key: JWT_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: elder-flow-secrets
              key: OPENAI_API_KEY
        volumeMounts:
        - name: knowledge-base
          mountPath: /app/knowledge_base
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: knowledge-base
        persistentVolumeClaim:
          claimName: knowledge-base-pvc
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: elder-flow-api-service
  namespace: elder-flow
  labels:
    app: elder-flow
    component: api
spec:
  selector:
    app: elder-flow
    component: api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-base-pvc
  namespace: elder-flow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: elder-flow-api-hpa
  namespace: elder-flow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: elder-flow-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
