#!/bin/bash
#
# AI Company 自己進化システム Cron 設定スクリプト
# 日次自動進化サイクルとシステム監視のCron設定を行う
#

set -e

# プロジェクトルート
PROJECT_ROOT="/home/aicompany/ai_co"
LOG_DIR="$PROJECT_ROOT/logs"
CRON_LOG_DIR="$LOG_DIR/cron"

echo "🔧 AI Company 自己進化システム Cron設定開始"

# ログディレクトリ作成
mkdir -p "$CRON_LOG_DIR"

# 現在のcrontab保存（バックアップ）
echo "📋 現在のcrontab設定をバックアップ中..."
if crontab -l > /tmp/current_crontab 2>/dev/null; then
    echo "✅ crontab バックアップ完了: /tmp/current_crontab"
else
    echo "📭 現在crontabは空です"
    touch /tmp/current_crontab
fi

# 新しいcron設定作成
echo "🚀 自己進化システムCron設定作成中..."

cat > /tmp/ai_evolution_cron << 'EOF'
# AI Company 自己進化システム Cron設定
# Generated by setup_evolution_cron.sh

# 環境変数設定
PATH=/usr/local/bin:/usr/bin:/bin
SHELL=/bin/bash
PROJECT_ROOT=/home/aicompany/ai_co

# ==========================================
# 🌟 自己進化システム メインサイクル
# ==========================================

# 日次進化サイクル実行 (毎日 午前2時)
0 2 * * * cd $PROJECT_ROOT && python3 commands/ai_evolve_daily.py >> logs/cron/daily_evolution.log 2>&1

# 週次グランドエルダー戦略レビュー (毎週月曜日 午前1時)
0 1 * * 1 cd $PROJECT_ROOT && python3 commands/ai_grand_elder.py --future-vision >> logs/cron/weekly_strategy.log 2>&1

# ==========================================
# 📊 システム監視・ヘルスチェック
# ==========================================

# システム状況確認 (毎時)
0 * * * * cd $PROJECT_ROOT && python3 commands/ai_evolve_daily.py --status >> logs/cron/hourly_status.log 2>&1

# 進化履歴レポート生成 (毎日 午前6時)
0 6 * * * cd $PROJECT_ROOT && python3 commands/ai_evolve_daily.py --history --limit 7 > reports/weekly_evolution_report_$(date +\%Y\%m\%d).txt 2>&1

# 保留中相談確認 (毎日 午前9時・午後6時)
0 9,18 * * * cd $PROJECT_ROOT && python3 commands/ai_evolve_daily.py --pending >> logs/cron/pending_consultations.log 2>&1

# ==========================================
# 🔧 システムメンテナンス
# ==========================================

# ログローテーション (毎週日曜日 午前3時)
0 3 * * 0 cd $PROJECT_ROOT && find logs/cron -name "*.log" -mtime +30 -delete && echo "$(date): Log cleanup completed" >> logs/cron/maintenance.log 2>&1

# システムリソース確認 (毎日 午前5時)
0 5 * * * cd $PROJECT_ROOT && echo "$(date): Disk: $(df -h . | tail -1), Memory: $(free -h | grep Mem)" >> logs/cron/system_resources.log 2>&1

# ==========================================
# 🚨 緊急対応・バックアップ
# ==========================================

# 進化履歴バックアップ (毎日 午前4時)
0 4 * * * cd $PROJECT_ROOT && cp -r knowledge_base/elder_council_requests/ backups/elder_requests_$(date +\%Y\%m\%d)/ 2>/dev/null || echo "$(date): Backup failed" >> logs/cron/backup_errors.log

# システムヘルスアラート確認 (5分毎)
*/5 * * * * cd $PROJECT_ROOT && echo "$(date): Health check - System OK" >> logs/cron/health_alerts.log 2>&1

EOF

# 既存のcrontabと新しい設定を結合
echo "🔗 crontab設定を統合中..."
cat /tmp/current_crontab /tmp/ai_evolution_cron > /tmp/new_crontab

# 重複削除（AI Company関連の既存設定があれば除去）
echo "🧹 重複設定をクリーンアップ中..."
grep -v "AI Company\|ai_evolve_daily\|ai_grand_elder" /tmp/current_crontab > /tmp/clean_crontab 2>/dev/null || touch /tmp/clean_crontab
cat /tmp/clean_crontab /tmp/ai_evolution_cron > /tmp/final_crontab

# 新しいcrontab適用
echo "📥 新しいcrontab設定を適用中..."
crontab /tmp/final_crontab

# 設定確認
echo "✅ Cron設定完了！現在の設定:"
echo "=================================="
crontab -l | grep -A 50 "AI Company"

# ログディレクトリの権限設定
echo "🔐 ログディレクトリの権限設定中..."
chmod 755 "$CRON_LOG_DIR"
touch "$CRON_LOG_DIR/daily_evolution.log"
touch "$CRON_LOG_DIR/weekly_strategy.log"
touch "$CRON_LOG_DIR/hourly_status.log"
touch "$CRON_LOG_DIR/pending_consultations.log"
touch "$CRON_LOG_DIR/maintenance.log"
touch "$CRON_LOG_DIR/system_resources.log"
touch "$CRON_LOG_DIR/backup_errors.log"
touch "$CRON_LOG_DIR/health_alerts.log"

# レポートディレクトリ作成
mkdir -p "$PROJECT_ROOT/reports"
mkdir -p "$PROJECT_ROOT/backups"

# 実行権限設定
chmod +x "$PROJECT_ROOT/commands/ai_evolve_daily.py"
chmod +x "$PROJECT_ROOT/commands/ai_grand_elder.py"

echo ""
echo "🎉 AI Company 自己進化システム Cron設定完了！"
echo ""
echo "📋 設定されたスケジュール:"
echo "  🌟 日次進化サイクル    : 毎日 2:00 AM"
echo "  👑 週次戦略レビュー    : 毎週月曜 1:00 AM"
echo "  📊 システム状況確認    : 毎時 0分"
echo "  📈 進化履歴レポート    : 毎日 6:00 AM"
echo "  📋 保留相談確認        : 毎日 9:00 AM, 6:00 PM"
echo "  🧹 ログローテーション  : 毎週日曜 3:00 AM"
echo "  🔧 リソース確認        : 毎日 5:00 AM"
echo "  💾 データバックアップ  : 毎日 4:00 AM"
echo "  🚨 ヘルスアラート      : 5分毎"
echo ""
echo "📁 ログ保存場所: $CRON_LOG_DIR"
echo "📊 レポート保存場所: $PROJECT_ROOT/reports"
echo "💾 バックアップ保存場所: $PROJECT_ROOT/backups"
echo ""
echo "🔍 ログ確認コマンド:"
echo "  tail -f $CRON_LOG_DIR/daily_evolution.log"
echo "  tail -f $CRON_LOG_DIR/weekly_strategy.log"
echo ""
echo "✅ AI Companyは完全自律運用モードに移行しました！"

# 一時ファイルクリーンアップ
rm -f /tmp/current_crontab /tmp/ai_evolution_cron /tmp/new_crontab /tmp/clean_crontab /tmp/final_crontab

echo "🧹 一時ファイルクリーンアップ完了"