#!/bin/bash
# 新しいBot Tokenに更新するスクリプト

echo "🔄 Slack Bot Token更新手順"
echo "=========================="
echo ""
echo "1. https://api.slack.com/apps にアクセス"
echo "2. OAuth & Permissions → Bot Token Scopes で以下を追加:"
echo "   - channels:history"
echo "   - channels:read"
echo "   - chat:write"
echo "   - app_mentions:read"
echo ""
echo "3. Install to Workspace をクリック"
echo "4. 新しいBot Token (xoxb-...) をコピー"
echo ""
echo "5. 以下のコマンドで.envを更新:"
echo ""
echo "sed -i 's|SLACK_BOT_TOKEN=xoxb-.*|SLACK_BOT_TOKEN=新しいトークン|' .env"
echo ""
echo "6. Slackワーカーを再起動:"
echo "pkill -f slack_polling_worker"
echo "sleep 2"
echo "ai-start slack"