version: '3.8'

services:
  # Web application server
  ai-company-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=testing
      - FLASK_DEBUG=false
    volumes:
      - ./web:/app/web
      - ./config:/app/config
    networks:
      - gui-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Selenium Chrome testing
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC port for viewing tests
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - gui-test-network
    depends_on:
      ai-company-web:
        condition: service_healthy

  # Selenium Firefox testing
  selenium-firefox:
    image: selenium/standalone-firefox:latest
    environment:
      - DISPLAY=:99
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    ports:
      - "4445:4444"
      - "7901:7900"  # VNC port for viewing tests
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - gui-test-network
    depends_on:
      ai-company-web:
        condition: service_healthy

  # GUI test runner
  gui-test-runner:
    build:
      context: .
      dockerfile: Dockerfile.gui-test-runner
    environment:
      - SELENIUM_HUB_HOST=selenium-chrome
      - SELENIUM_HUB_PORT=4444
      - APP_BASE_URL=http://ai-company-web:5555
      - TEST_BROWSER=chrome
    volumes:
      - ./:/app
      - ./test_screenshots:/app/test_screenshots
      - ./test_results:/app/test_results
    networks:
      - gui-test-network
    depends_on:
      - selenium-chrome
      - ai-company-web
    command: python3 /app/comprehensive_gui_test.py

  # Playwright testing (alternative)
  playwright-test-runner:
    build:
      context: .
      dockerfile: Dockerfile.playwright-test
    environment:
      - APP_BASE_URL=http://ai-company-web:5555
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - ./:/app
      - ./test_screenshots:/app/test_screenshots
      - ./test_results:/app/test_results
    networks:
      - gui-test-network
    depends_on:
      ai-company-web:
        condition: service_healthy
    command: python3 /app/libs/playwright_gui_test_framework.py

networks:
  gui-test-network:
    driver: bridge

volumes:
  test_screenshots:
  test_results:
