# Elders Guild - Worker Systems
# 4賢者システム、タスク処理、バックグラウンドワーカー

version: '3.8'

services:
  # 4賢者システム統合サービス
  four-sages:
    build:
      context: .
      dockerfile: Dockerfile.workers
    container_name: elders-guild-four-sages
    environment:
      - DATABASE_URL=postgresql://elder_admin:sage_wisdom_2025@postgres:5432/elders_guild
      - REDIS_URL=redis://redis:6379/2
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PROJECT_NAME=four-sages
    volumes:
      - ./workers:/app/workers
      - ./libs:/app/libs
      - ./core:/app/core
      - ./knowledge_base:/app/knowledge_base
    depends_on:
      - postgres
      - redis
    networks:
      - elders-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # タスクエルダー（タスク管理）
  task-elder:
    build:
      context: .
      dockerfile: Dockerfile.workers
    container_name: elders-guild-task-elder
    environment:
      - DATABASE_URL=postgresql://elder_admin:sage_wisdom_2025@postgres:5432/elders_guild
      - REDIS_URL=redis://redis:6379/3
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PROJECT_NAME=task-elder
    volumes:
      - ./workers:/app/workers
      - ./libs:/app/libs
      - ./core:/app/core
    depends_on:
      - postgres
      - redis
    networks:
      - elders-network
    command: ["python", "-m", "workers.task_elder_main"]
    restart: unless-stopped

  # RAGウィザーズ（情報探索）
  rag-wizards:
    build:
      context: .
      dockerfile: Dockerfile.workers
    container_name: elders-guild-rag-wizards
    environment:
      - DATABASE_URL=postgresql://elder_admin:sage_wisdom_2025@postgres:5432/elders_guild
      - REDIS_URL=redis://redis:6379/4
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PROJECT_NAME=rag-wizards
    volumes:
      - ./workers:/app/workers
      - ./libs:/app/libs
      - ./core:/app/core
      - ./knowledge_base:/app/knowledge_base
    depends_on:
      - postgres
      - redis
    networks:
      - elders-network
    command: ["python", "-m", "workers.rag_wizards_main"]
    restart: unless-stopped

  # インシデント騎士団（緊急対応）
  incident-knights:
    build:
      context: .
      dockerfile: Dockerfile.workers
    container_name: elders-guild-incident-knights
    environment:
      - DATABASE_URL=postgresql://elder_admin:sage_wisdom_2025@postgres:5432/elders_guild
      - REDIS_URL=redis://redis:6379/5
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PROJECT_NAME=incident-knights
    volumes:
      - ./workers:/app/workers
      - ./libs:/app/libs
      - ./core:/app/core
    depends_on:
      - postgres
      - redis
    networks:
      - elders-network
    command: ["python", "-m", "workers.incident_knights_main"]
    restart: unless-stopped

  # エルフの森（監視・メンテナンス）
  elf-forest:
    build:
      context: .
      dockerfile: Dockerfile.workers
    container_name: elders-guild-elf-forest
    environment:
      - DATABASE_URL=postgresql://elder_admin:sage_wisdom_2025@postgres:5432/elders_guild
      - REDIS_URL=redis://redis:6379/6
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PROJECT_NAME=elf-forest
    volumes:
      - ./workers:/app/workers
      - ./libs:/app/libs
      - ./core:/app/core
    depends_on:
      - postgres
      - redis
    networks:
      - elders-network
    command: ["python", "-m", "workers.elf_forest_main"]
    restart: unless-stopped

networks:
  elders-network:
    external: true
